services:
  - type: web
    name: voice-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # Устанавливаем в панели управления
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: info
