services:
  - type: web
    name: mini-voice-assistant
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # Значение добавляется вручную в панели Render
      - key: PYTHONUNBUFFERED
        value: true
      - key: PORT
        value: 8000
